#+title: Ανάλυση & Σχεδίαση Συστημάτων Λογισμικού
#+subtitle: Εαρινό Εξάμηνο 2023
#+author: Αναστάσιος-Φαίδων Σεϊτανίδης\thanks{Student ID: 1115202000179}, Κωνσταντίνος Χούσος\thanks{Student ID: 1115202000215}
#+language: gr
#+options: num:t toc:t date:nil timestamp:nil
#+export_file_name: 1115202000215_1115202000179.pdf
:LATEX_PROPERTIES:
#+LATEX_CLASS: article

#+LATEX_CLASS_OPTIONS: [a4paper, titlepage, twoside]

#+LATEX_HEADER: \usepackage{newcomputermodern}

#+LATEX_HEADER: \usepackage{polyglossia}
#+LATEX_HEADER: \setmainlanguage{greek}
#+LATEX_HEADER: \setotherlanguage{english}

#+LATEX_HEADER: \renewcommand*{\thefootnote}{\fnsymbol{footnote}}

#+LATEX_HEADER: \pagestyle{headings}

#+LATEX_HEADER: \usepackage{microtype}

#+LATEX_HEADER: \renewcommand{\baselinestretch}{1.2}

#+LATEX_HEADER: \usepackage[margin=1.4in]{geometry}

#+LATEX_HEADER: \usepackage[font={small}, labelfont={}]{caption}
:END:

* [0/4] Ζητούμενα :noexport:

** TODO Εισαγωγή (έως 500 λέξεις) στην οποία θα περιγράψετε:

- το τμήμα της εργασίας που ανέλαβε το κάθε μέλος της ομάδας

- με ποιο τρόπο συνεργαστήκατε (π.χ. με εβδομαδιαίες συναντήσεις, εξ αποστάσεως, δια ζώσης κ.λπ.)

- Τυχόν παραδοχές που κάνατε για την εργασία (αν δεν σας κάλυψαν οι υφιστάμενες οδηγίες/περιγραφές των διαδικασιών)

- τι περιλαμβάνει τα κάθε ένα από τα κεφάλαια της εργασίας.

** TODO [0/5] Μέρος Α: UML

1. [-] [1/2]

   - [X] Για τη διαδικασία 1 περιγράψτε μέσω σεναρίων τις περιπτώσεις χρήσης που εντοπίσατε, καθώς και τις πιθανές επεκτάσεις τους

     - Όταν γίνεται ο αιτών υποψήφιος, λειτουργικά δεν αλλάζει κάτι και για αυτό παραλείπεται ως /χειριστής/.
     - Η /Ενημέρωση Βάσης Δεδομένων Χρηστών/ είναι κι αυτή γιατί έχει κι αυτή επεκτείνουσα.

   - [-] [3/4] Για κάθε μια από τις διαδικασίες 1, 2, 3 & 4 δημιουργήστε από ένα διάγραμμα περιπτώσεων χρήσης (Use Case Diagram, UML), εφαρμόζοντας όπου ενδεχομένως χρειάζεται σχέσεις γενίκευσης, επέκτασης ή/και συμπερίληψης.

     - [X] Διαδικασία 1
     - [X] Διαδικασία 2
       Η ιδιότητα του εγγεγραμμένου χρήστη από μόνη της δεν δίνει κάτι. Για αυτό είναι στις υποκλάσσεις οι λειτουργίες.
     - [X] Διαδικασία 3
     - [ ] Διαδικασία 4

2. [ ] [0/4] Δημιουργήστε από ένα διάγραμμα κλάσεων (Class Diagram, UML) για τις διαδικασίες 1, 2, 3 & 4. Σε κάθε κλάση να αποτυπώνονται:

   + Το όνομα της κλάσης

   + Τα ονόματα και οι τύποι των σημαντικών χαρακτηριστικών και μεθόδων, καθώς και χαρακτηριστικά πρόσβασης (public, private, protected)

   + τυχόν συσχετίσεις ή/και πληθικότητες μεταξύ των κλάσεων.

     1) Στις συσχετίσεις περιλαμβάνονται και τυχόν σχέσεις κληρονομικότητας.

     2) Στα διαγράμματα κλάσεων δεν χρειάζεται να αποτυπωθούν λέξεις-κλειδιά τυχόν εξαρτήσεων. 

   + [ ] Διαδικασία 1
   + [ ] Διαδικασία 2
   + [ ] Διαδικασία 3
   + [ ] Διαδικασία 4

3. [ ] Δημιουργήστε ένα διάγραμμα μηχανής καταστάσεων (Statechart Diagram, UML) για την κλάση Εκπαιδευόμενος (να λάβετε υπόψη τις περιγραφές των σχετικών διαδικασιών).

4. [ ] [0/3] Δημιουργήστε διαγράμματα ακολουθίας (Sequence Diagram, UML) ως εξής:

   + [ ] Ένα για τη διαδικασία 1.
   + [ ] Ένα για τη διαδικασία 3.
   + [ ] Ένα για τη διαδικασία 4.

     + Οι οντότητες (και τα μηνύματα) που θα εμφανίζονται στα διαγράμματα ακολουθίας θα πρέπει να προκύπτουν από τις κλάσεις (και από τις μεθόδους αυτών) που θα έχετε μοντελοποιήσει στα αντίστοιχα διαγράμματα κλάσεων.

5. [ ] Ένα διάγραμμα δραστηριοτήτων (Activity Diagram, UML), για μια διαδικασία της επιλογής σας. Θα πρέπει να χωρίσετε το διάγραμμα δραστηριοτήτων σε διαμερίσματα που δείχνουν ποιος Actor (ή ποιο τμήμα του οργανισμού) κάνει την κάθε ενέργεια.

** TODO Μέρος Β: Δομημένη Ανάλυση

1. [0/3] Δημιουργήστε μια ομάδα Διαγραμμάτων Ροής Δεδομένων (ΔΡΔ) ως εξής:

   + [ ] ένα Γενικό ΔΡΔ (Επίπεδο Αφαίρεσης: 0) για τη συνολική λειτουργία του φορέα

   + [ ] ένα ΔΡΔ (Επίπεδο Αφαίρεσης: 1) για τη συνολική λειτουργία του φορέα

   + [ ] ένα ΔΡΔ (Επίπεδο Αφαίρεσης: 2) για τη διαδικασία 2

** TODO Επίλογος, ο οποίος θα είναι μια αναφορά (έως 500 λέξεις) που θα περιλαμβάνει:

- τα συμπεράσματά σας από τη δημιουργία των διαγραμμάτων (π.χ. πλεονεκτήματα ή δυσκολίες που αντιμετωπίσατε, βαθμός δυσκολίας της εργασίας, επάρκεια χρόνου κ.ά.)

- προτάσεις βελτίωσης της εργασίας.

* Εισαγωγή

** Notes :noexport:

*** Ποιος έκανε τι;

**** Φαίδωνας

- Περιγραφή διαδικασίας 1 μέσω σεναρίων
- Use case diagram 1ης διαδικασίας

